# Site settings
title: InMōshn
email: your-email@yourdomain.com
copyright_name: InMōshn
description: "This blog will be regularly updated with updates from the team behind InMōshn regarding your next mode of personal tranportation."
baseurl: "/blog/_site"
url: "https://prateekmadhikar.github.io/inmoshn_website"

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate]
